### ISSUE TITLE
emr_filter.create with NULL name creates the same filter name independent of operator

### ISSUE THREAD

**Issue by nettam** [tanaylab/naryn#111]
f_bigger <- emr_filter.create(NULL, src='lab.101', time.shift=c(-1,0)*year(), operator='>', val=12)
f_smaller <- emr_filter.create(NULL, src='lab.101', time.shift=c(-1,0)*year(), operator='<', val=12)

identical(f_bigger, f_smaller)
[1]TRUE

This causes the second definition to override the first one....

**Comment by aviezerl** [comment]
fixed
